# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

places = [
  ["Asia/Pacific", "Ahmedabad"],
  ["Asia/Pacific", "Almaty"],
  ["Asia/Pacific", "Bangkok"],
  ["Asia/Pacific", "Beijing"],
  ["Asia/Pacific", "Bengaluru"],
  ["Asia/Pacific", "Chengdu"],
  ["Asia/Pacific", "Chennai"],
  ["Asia/Pacific", "Coimbatore"],
  ["Asia/Pacific", "Colombo"],
  ["Asia/Pacific", "Dalian"],
  ["Asia/Pacific", "Delhi"],
  ["Asia/Pacific", "Dhaka "],
  ["Asia/Pacific", "Guangzhou "],
  ["Asia/Pacific", "Hangzhou"],
  ["Asia/Pacific", "Hanoi"],
  ["Asia/Pacific", "Harbin"],
  ["Asia/Pacific", "Ho Chi Minh City"],
  ["Asia/Pacific", "Hong Kong"],
  ["Asia/Pacific", "Hyderabad"],
  ["Asia/Pacific", "Islamabad"],
  ["Asia/Pacific", "Jakarta"],
  ["Asia/Pacific", "Karachi"],
  ["Asia/Pacific", "Kolkata"],
  ["Asia/Pacific", "Kuala Lumpur"],
  ["Asia/Pacific", "Lahore"],
  ["Asia/Pacific", "Manila"],
  ["Asia/Pacific", "Melbourne"],
  ["Asia/Pacific", "Mumbai"],
  ["Asia/Pacific", "Nanjing"],
  ["Asia/Pacific", "Osaka"],
  ["Asia/Pacific", "Pune"],
  ["Asia/Pacific", "Qingdao"],
  ["Asia/Pacific", "Seoul"],
  ["Asia/Pacific", "Shanghai"],
  ["Asia/Pacific", "Shenzhen"],
  ["Asia/Pacific", "Singapore"],
  ["Asia/Pacific", "Sydney"],
  ["Asia/Pacific", "Taipei"],
  ["Asia/Pacific", "Tianjin"],
  ["Asia/Pacific", "Tokyo"],
  ["Asia/Pacific", "Xi an"],
  ["Asia/Pacific", "Xiamen"],
  ["Europe", "Amsterdam"],
  ["Europe", "Ankara"],
  ["Europe", "Athens"],
  ["Europe", "Barcelona"],
  ["Europe", "Berlin"],
  ["Europe", "Brussels"],
  ["Europe", "Bucharest"],
  ["Europe", "Budapest"],
  ["Europe", "Copenhagen"],
  ["Europe", "Dublin"],
  ["Europe", "Dusseldorf"],
  ["Europe", "Edinburgh"],
  ["Europe", "Frankfurt"],
  ["Europe", "Geneva"],
  ["Europe", "Hamburg"],
  ["Europe", "Istanbul"],
  ["Europe", "Kiev"],
  ["Europe", "Lisbon"],
  ["Europe", "London"],
  ["Europe", "Madrid"],
  ["Europe", "Milan"],
  ["Europe", "Minsk"],
  ["Europe", "Moscow"],
  ["Europe", "Munich"],
  ["Europe", "Novosibirsk"],
  ["Europe", "Paris"],
  ["Europe", "Prague"],
  ["Europe", "Rome"],
  ["Europe", "Sofia"],
  ["Europe", "St Petersburg"],
  ["Europe", "Stockholm"],
  ["Europe", "Vienna"],
  ["Europe", "Vladivostok"],
  ["Europe", "Warsaw"],
  ["Europe", "Yekaterinburg"],
  ["Europe", "Zurich"],
  ["Latin America", "Belo Horizonte"],
  ["Latin America", "Bogota"],
  ["Latin America", "Brasilia"],
  ["Latin America", "Buenos Aires"],
  ["Latin America", "Caracas"],
  ["Latin America", "Cordoba"],
  ["Latin America", "Curitiba"],
  ["Latin America", "Lima"],
  ["Latin America", "Medellin"],
  ["Latin America", "Mexico City"],
  ["Latin America", "Monterrey"],
  ["Latin America", "Montevideo"],
  ["Latin America", "Quito"],
  ["Latin America", "Recife"],
  ["Latin America", "Rio de Janeiro"],
  ["Latin America", "San Jose"],
  ["Latin America", "Punta Cana* "],
  ["Latin America", "Santo Domingo"],
  ["Latin America", "São Paulo"],
  ["Middle East and Africa", "Abu Dhabi"],
  ["Middle East and Africa", "Accra"],
  ["Middle East and Africa", "Amman"],
  ["Middle East and Africa", "Beira"],
  ["Middle East and Africa", "Beirut"],
  ["Middle East and Africa", "Cairo"],
  ["Middle East and Africa", "Cape Town"],
  ["Middle East and Africa", "Casablanca"],
  ["Middle East and Africa", "Dakar"],
  ["Middle East and Africa", "Damascus"],
  ["Middle East and Africa", "Dubai"],
  ["Middle East and Africa", "Durban"],
  ["Middle East and Africa", "Kampala"],
  ["Middle East and Africa", "Johannesburg"],
  ["Middle East and Africa", "Lagos"],
  ["Middle East and Africa", "Maputo"],
  ["Middle East and Africa", "Nairobi"],
  ["Middle East and Africa", "Riyadh"],
  ["Middle East and Africa", "Tehran"],
  ["Middle East and Africa", "Tel Aviv"],
  ["Middle East and Africa", "Tunis"],
  ["North America", "Atlanta"],
  ["North America", "Boston"],
  ["North America", "Chicago"],
  ["North America", "Dallas"],
  ["North America", "Houston"],
  ["North America", "Los Angeles"],
  ["North America", "Miami"],
  ["North America", "Montreal"],
  ["North America", "New York"],
  ["North America", "Philadelphia"],
  ["North America", "San Francisco"],
  ["North America", "Toronto"],
  ["North America", "Vancouver"],
  ["North America", "Washington"]
]

places.each do |r, c|
  Place.where(region: r, city: c).first_or_create!
end
